[package]
name = "wolfwig"
version = "0.0.1"
authors = ["Stephen Longfield <stephen.longfield@gmail.com>"]

[dependencies]
clippy =  {version = "*", optional = true}
log = "0.4"

[features]
default = []
