# Rough notes on the Gameboy config.

module:
  name: CPU
  mnemonic: lr25902
  memory:
    name: Working RAM
    mnemonic: wram
    banks: 8 # One in DMG mode, 8 in CGB mode
    address: 0xC000
    size: 0x1000

module:
  name: Cartridge
  mnemonic: cartridge
  memory:
    name: Read-Only Memory
    mnemonic: rom
    banks: ? # Configurable

  memory:
    name: Extended RAM
    mnemonic: xram
    banks: ? # Configurable
    address: 0xA000
    size: 0x2000
